### PR TITLE
SOMNI-5845: Join UI & Common submodules & Translate into Swift 2/2

### PR DESCRIPTION
**Pull request by LauraSchlegel**
Note: this PR depends on and needs to be processed the same time as sage_accounting_ios PR feature-SOMNI-5845.

Note 2: sage_one_mobile_ui is no longer needed.

### CODE REVIEW

**Comment by didacsage** [comment]
Also seems to repeat in loop the full refresh when login in... I will check it tomorrow as well.

**Comment by didacsage** [comment]
The full refresh loop comes from dataDidFlow notification posted from watch session, we should improve it because it is forcing an API error for:
`error code:
429
message:
Rate limit is exceeded
`

**Comment by LauraSchlegel** [comment]
Hi @didacsage!  Regarding the crash when enters to profile taxes in Canada, when try to access to immutabilityProvider.prefix:  I just fixed that.

**Comment by LauraSchlegel** [comment]
> The full refresh loop comes from dataDidFlow notification posted from watch session, we should improve it because it is forcing an API error for:
> `error code: 429 message: Rate limit is exceeded`

Yeah I pointed this out back in June before I left for holidays.  https://sageone.slack.com/archives/GKF6U5Z4Y/p1561522840014400

**Comment by didacsage** [comment]
A solution could be not do a full refresh when receive the notification, just fetch the coredata

**Comment by LauraSchlegel** [comment]
I can go ahead and make that change for the watch app issue if you want?  I'll enter a separate jira ticket/PR for that as it's not related to this ticket.  Sound good?

**Comment by LauraSchlegel** [comment]
@didacsage I added a separate jira ticket for the watch refresh issue, https://jira.sage.com/browse/SOMNI-5993 as it's not related to this PR.

Can you please continue review of this PR (join of UI and common submodules)?  As I'm sure you've also experienced it is a pain switching back and forth between develop and this branch with the carthage module changes. :(

**Pull request merged**
